### ISSUE TITLE
[Bug]: ssh recording exception in online sessions

### ISSUE THREAD

**Issue by hooye** [veops/oneterm#20]
### Contact Details

hoofor@163.com

### This bug is related to UI or API?

UI

### What happened?

A bug happened!,  When I use [zellij](https://zellij.dev/) for end point split screen operation, there is a problem with session moderation. After splitting the screen, there are actually multiple screens recorded, oneterm is still recording the entire screen, and the operation content cannot be displayed correctly. This problem only occurs in online sessions

### Version

newest

### What browsers are you seeing the problem on?

Chrome

**Comment by ttktatakai** [comment]
@fxiang21

**Comment by fxiang21** [comment]
@hooye Thank you for your feedback, we will reproduce and fix the issue as soon as possible.

**Comment by ttktatakai** [comment]
Did you mean this situation?
1. your connection session 
![image](https://github.com/veops/oneterm/assets/150361932/a1efd7ab-e3a7-4187-831e-02e1988f3412)

2. But in your monit session, there is no pane lines
![image](https://github.com/veops/oneterm/assets/150361932/5816effe-c2da-4276-964d-b4ed91b0e090)

3. If so, you can try to select different pane, then the pane lines should be shown normally. The reason is zellij does not transfer pane lines but only the result of your commands(like ls in above),i.e., when you start a monit session, you can only monit new data, any old data(like pane lines) would not be shown.
